### ISSUE TITLE
Molten does not work with cross site requests to API

### ISSUE THREAD

**Issue by martinhoefling** [martinhoefling/molten#23]

**Comment by martinhoefling** [comment]
@bbinet: can you check if this fix works for you, too?

**Comment by bbinet** [comment]
Sure, I will test your fix on monday.
Thanks!

**Comment by bbinet** [comment]
I confirm that your fix works for me, thanks a lot!

**Comment by bbinet** [comment]
But I get another issue with function doc completion, see: #25.
