### ISSUE TITLE
Add screenshots to documentation

### ISSUE THREAD

**Issue by bmcorser** [martinhoefling/molten#26]
Sounds like a nice project ... but does it look :sparkling_heart: ? It would be great to see some images showing off the GUI (perhaps in `README.md` or wiki?)

**Comment by martinhoefling** [comment]
@bmcorser: thanks for the comment - I am actually planning this for the next version. If you want to get a quick impression, you can clone / vagrant up the dev instance but I agree - screenshots give you a immediate impression.

**Comment by bmcorser** [comment]
Cool, I'll try getting the dev instance up -- will post screenshots here if I do.

I just looked over the vagrant bits, I like the idea to include test infra in this way. To play with the GUI I'd also have to build wouldn't I (there doesn't seem to be anything in the `dist` directory)? That would mean setting up a Node environment etc :scream: ... again, will post here if I get something `:)`

**Comment by martinhoefling** [comment]
Yep, for `dev` you need a complete node setup. So the idea is to keep the common setup part in `/vagrant/vagrant/bootstrap-dev.sh`. I plan to publish a salt formula for setting up molten together with 0.2 and also use that one in the vagrant file replacing most of the custom setup code in `/vagrant/vagrant/bootstrap-dev.sh`. You can also use `demo` vagrant box which does not require node to be set up but 0.2 will be out soon with quite some improvements.

**Comment by martinhoefling** [comment]
Screenshots added: https://github.com/martinhoefling/molten/blob/master/screenshots/Screenshots.md

**Comment by bmcorser** [comment]
Oh very nice. Thanks
