### ISSUE TITLE
Allow json to be viewed in browser in addition to download

### ISSUE THREAD

**Issue by beardedeagle** [martinhoefling/molten#27]
I see the ability to download my job info's json, but it would be equally great to be able to see that in the browser. As an added bonus, seeing job output in yaml would be awesome.

**Comment by martinhoefling** [comment]
@beardedeagle, json download was already build in development version. Concerning yaml: where do you consider that useful? Also as download?

**Comment by beardedeagle** [comment]
Right, sorry poorly worded: Viewing json _IN_ browser would be a great addition to the _already_ present feature of being able to download it.

No real advantage to allowing returned data to also be rendered as yaml other than that those who are migrating from CLI based operations would feel more at home since that is all we have ever seen till along came things like Molten and SaltPad.

**Comment by martinhoefling** [comment]
I am preparing 0.2 atm, will consider this for 0.3. How about a setting if json/yaml is prefered and an additional button for opening it instead of downloading? Not sure what you mean by yaml display, but I also plan to replace my custom object display with react-json-tree once it has an option to hide the root.

**Comment by beardedeagle** [comment]
That would work. Would it open it in page or in a separate page?

**Comment by martinhoefling** [comment]
Separate page/new window? Probably easier  to copy/paste, right?

**Comment by beardedeagle** [comment]
I would agree.

**Comment by martinhoefling** [comment]
@beardedeagle - feature added. You can try it out with the current dev version.
