### ISSUE TITLE
reverse sorting of jobs

### ISSUE THREAD

**Issue by bbinet** [martinhoefling/molten#30]
It would be great to have the list of jobs sorted in the reverse order so that we don't need to scroll down to the end of the list to see the latest job.

**Comment by martinhoefling** [comment]
Good idea

**Comment by beardedeagle** [comment]
Or the ability to select ascending/descending order.

**Comment by martinhoefling** [comment]
@beardedeagle Selecting sorting order is an option. For the minion tab, it makes no sense but for the jobs tab it does. Atm, I think that having the newest ones on top makes sense for both (as merged in #31 from @bbinet ). Feel free to open an issue if you thing toggling the order in the jobs tab is an important feature.
