### ISSUE TITLE
Need doc for non-vargrant installation

### ISSUE THREAD

**Issue by tjyang** [martinhoefling/molten#33]
This is a RFE. 
Is it possible you can publish a guide  manual installation ?

**Comment by martinhoefling** [comment]
You can use the molten formula https://github.com/martinhoefling/molten-formula. or follow the manual installation instructions https://github.com/martinhoefling/molten/blob/master/doc/Setup.md#manual-setup. If there's anything unclear, please re-open and/or create a pull request.

**Comment by martinhoefling** [comment]
Just added https://github.com/martinhoefling/molten/commit/dbf781e175fb61347de597b4e16ef02c2a21eedd
Maybe it was not clear that 'Installation' is found under 'Configuration' :-)

**Comment by tjyang** [comment]
Thanks for the quick response, above change on readme.md is much better.
