### ISSUE TITLE
eauth configuration

### ISSUE THREAD

**Issue by LordFPL** [martinhoefling/molten#34]
Hi, and thanks for this project :)

Have you any plan for supporting other eauth ? Seem to be planned in https://github.com/martinhoefling/molten/blob/master/app/ActionCreators.js#L68

I have try to modify "pam" by "ldap" (and run build/release), but i get a blank page... any idea ?

Thx in advance :)

**Comment by martinhoefling** [comment]
It is planned. So if you need it I can try to build it the next week or so...
Shouldn't be too complicated. However, I can't test it since I have no LDAP set up.

Release should create a directory with everything in it. Can you post output and steps to reproduce? Maybe also the output when you open the browser devtools.

**Comment by LordFPL** [comment]
Hello,

Actually i have all the file in the release directory : 

```
find molten -ls
402273    4 drwxr-xr-x   4 root     root         4096 Feb  3 11:33 molten
402284    4 -rw-r--r--   1 root     root         2243 Feb  3 11:32 molten/favicon.png
402278    4 -rw-r--r--   1 root     root          123 Feb  3 11:32 molten/config.js
402279    4 drwxr-xr-x   2 root     root         4096 Feb  3 11:32 molten/contrib
402280    4 -rw-r--r--   1 root     root         1453 Feb  3 11:32 molten/contrib/github.svg
402282    8 -rw-r--r--   1 root     root         4321 Feb  3 11:32 molten/contrib/toastr.min.js
402281   80 -rw-r--r--   1 root     root        77862 Feb  3 11:32 molten/contrib/animate.css
402283    8 -rw-r--r--   1 root     root         5737 Feb  3 11:32 molten/contrib/toastr.min.css
402276    4 -rw-r--r--   1 root     root          766 Feb  3 11:32 molten/index.html
402285    4 drwxr-xr-x   2 root     root         4096 Feb  3 11:33 molten/molten
402286  944 -rw-r--r--   1 root     root       964144 Feb  3 11:33 molten/molten/molten.js
```

I have done the same thing as with your tar.gz... but i get a blank page... source is : 

```
<!DOCTYPE html>
<html>
<head>
    <title>Molten Salt API UI</title>
    <link rel="icon" type="image/png" href="/assets/favicon.png">
    <link href='/assets/contrib/toastr.min.css' rel='stylesheet' type='text/css'>
    <link href='/assets/contrib/animate.css' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>
</head>
<body>
<div id='content'>
</div>
<script type='text/javascript' src='/assets/config.js'></script>
<script type='text/javascript' src='/assets/molten/molten.js'></script>
<script type='text/javascript' src='/assets/contrib/toastr.min.js'></script>
</body>
</html>
```

If i try to display the molten.js, the modification is in place : 

```
(...),M.createSession({basepath:x["default"].API_BASE_URL,username:e,password:t,eauth:"ldap"},function(e){return n(s(e))},f(...)
```

I don't know how to open the devtools.

**Comment by martinhoefling** [comment]
On chrome, you can open the devtools with ctrl + alt + i but there might be a dependency issue. I've built a prerelease with ldap support here https://github.com/martinhoefling/molten/releases/tag/v0.3.0pre1.

**Comment by LordFPL** [comment]
Sorry for late answer, i will test it tomorrow, many thx anyway :)

**Comment by LordFPL** [comment]
Just tested : it's woooooork !!!!! :)
Excellent ! ^_^
