### ISSUE TITLE
LDAP authentication doesn't work

### ISSUE THREAD

**Issue by sebw** [martinhoefling/molten#37]
Hi,

PAM auth works, LDAP auth doesn't.

I get this message:
salt 'Authentication not checked for user X from IP x.x.x.x'

Thanks

**Comment by martinhoefling** [comment]
So the message comes from salt / salt log? Is ldap auth working from the cli? (https://docs.saltstack.com/en/develop/topics/eauth/index.html#ldap-and-active-directory) I never used ldap auth so far and made this switch upon request. There is no logic in molten, it's just filling the eauth field in the request accordingly.

**Comment by sebw** [comment]
The message is from Salt API logs. LDAP is working fine from the CLI.

**Comment by martinhoefling** [comment]
Can you "curl" the authentication request (https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#authentication), e.g.

```
curl -sSk https://localhost:8000/login \
      -c ~/cookies.txt \
      -H 'Accept: application/x-yaml' \
      -d username=username \
      -d password=password \
      -d eauth=ldap
``` 
and paste the output? If it succeeds and you're familiar with the debugging tools of your browser, you can compare that to the request molten sends on login.

**Comment by fintanmm** [comment]
Hi,

Just a heads up. The following is what I had to do to get ldap working.
      ldap:
         MyGroup%:
          - grains.*
          - status.*
          - sys.*
          - test.*
          - '@jobs'

[See here](https://github.com/saltstack/halite/issues/164)

Regards,
Fintan

**Comment by martinhoefling** [comment]
Thx @fintanmm for confirming that it works. As I said, there is no logic in molten concerning ldap.
