### ISSUE TITLE
Events tab pause button and filter don't work 

### ISSUE THREAD

**Issue by almoore** [martinhoefling/molten#41]
The events tab has a pause button that when it is click there are no visible changes. The event count keeps going up and the event listener port stays open.
The event filter also does not create any noticeable changes as well. Ideally, this would show only the events that match that filter, clearing everything else for the time being. 

Also the event stream stays open for a long period of time. It would be nice to have the option to close or stop the event stream and then reload it when needed. I have noticed this will crash the session from time to time.

**Comment by martinhoefling** [comment]
Pause should pause all updates, not receiving new events. That would be another useful feature :-)

**Comment by martinhoefling** [comment]
Opened #42
