### ISSUE TITLE
Run molten on different host?

### ISSUE THREAD

**Issue by absolutejam** [martinhoefling/molten#44]
My Salt master runs in a Docker container; is there any way to run molten from a different container (or VM) than the master?

This would be especially useful as it would limit access to the master, only exposing molten.

**Comment by martinhoefling** [comment]
Molten itself runs in your browser only and consumes the salt rest api. You can serve the static files required for molten from a separate (nginx) container but you still need to be able to access the salt-api. You however can run the salt api in a different container but that's a different story which I never tried so far.

**Comment by absolutejam** [comment]
@martinhoefling Any idea if there's some existing docs regarding this? Can't seem to find any  info for running salt-api and Molten on different hosts.

**Comment by martinhoefling** [comment]
You can set the api endpoint in config.js:

https://github.com/martinhoefling/molten/blob/master/dist/config.js

Its documented here:
https://github.com/martinhoefling/molten/blob/master/doc/Setup.md#alternate-installation-on-different-host

Does that answer your question?

**Comment by absolutejam** [comment]
So, leave the `rest_cherrypy` settings alone (as per example), add the settings to `config.js` and serve the molten app with NGINX or the likes?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinhoefling** [comment]
Right - but you must have a salt rest api server running elsewhere.
